### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by Coke-das-JHL** [kumarapurv/Object-Detection-and-Depth-Sensing-for-a-Small-Autonomous-Racecar-System#1]
nvidia@jetson-0425018067856:~/racecar-ws/src/Object-Detection-and-Depth-Sensing-for-a-Small-Autonomous-Racecar-System$ python Racecar.py demo/2020-04-28-23-33-52.bag 

OpenCV Error: Parsing error (Unknown layer type: shortcut) in ReadDarknetFromCfgFile, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/dnn/src/darknet/darknet_io.cpp, line 503
Traceback (most recent call last):
  File "Racecar.py", line 81, in <module>
    net = cv2.dnn.readNetFromDarknet(model_config, model_weights)
cv2.error: /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/dnn/src/darknet/darknet_io.cpp:503: error: (-212) Unknown layer type: shortcut in function ReadDarknetFromCfgFile

do you know why this error happend? thank you
I'm using ROS kinetic with jetson tx2

**Comment by kumarapurv** [comment]
Hi @Coke-das-JHL ,
Sorry I haven't been active lately. Is the issue solved?
You will need Darknet installed. Do you have it? Please refer to [this](https://pjreddie.com/darknet/install/) website. 
And, thanks for pointing it out. I will have it mentioned in the document.
